config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sales#index"
  resources :sales, except: [:edit, :destroy] do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :items, class_name: 'SaleItem'

  default_scope { order(created_at: :desc) }

  def total_price
    self.items.map { |i| i.total_price }.sum
  end

  def total_amount
    self.items.sum(:amount)
  end

  def total_items
    self.items.count
  end

  def self.total_sales
    Sale.all.count
  end
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
  belongs_to :sale

  def total_price
    self.price * self.amount
  end

  def self.total_items
    SaleItem.all.count
  end

  def self.total_amount
    SaleItem.sum(:amount)
  end

  def self.total_price
    SaleItem.all.map { |i| i.total_price }.sum
  end
end

app/models/service/sale_file_normalize.rb
class Service::SaleFileNormalize

  def initialize(file)
    @file = file.path
  end

  def resolver
    items
  end

  private

  def read
    File.read(@file, :encoding => "UTF-8")
  end

  def items
    items = []
    read.each_line.with_index do |line, index|
      next if index == 0
      data = line.split("\t")
      buyer, description, price, amount, address, vendor =
        data.map{ |d| d }.flatten
      items << {
        buyer: buyer,
        description: description,
        price: price,
        amount: amount,
        address: address,
        vendor: vendor
      }
    end
    items
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
# encoding: UTF-8
class SalesController < ApplicationController
  def index
    @sales = Sale.all
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def import
    if params[:file].nil?
      flash[:danger] = "Por favor, selecione o arquivo."
      redirect_to new_sale_path
      return
    end
    flash[:success] = "Dados importado com sucesso."
    @sale = Sale.new
    normalize_items.each do |item|
      @sale.items << SaleItem.new(item)
    end
    @sale.save
  end

  private

  def normalize_items
    Service::SaleFileNormalize.new(params[:file]).resolver
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def notification
    messages = ""
    [:success, :danger].each {|type|
      if flash[type]
        messages += "<div class='alert alert-#{type}' role='alert'>#{flash[type]}</div>"
      end
    }
    messages.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AvaliacaoDesenvolvedor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sales/_dash.html.erb
<div class="row">
  <% if defined?(total_sales) %>
    <div class="col-sm-3 col-xs-12">
      <div class="dash">
        <div class="row">
          <div class="col-sm-6 col-xs-12">
            Vendas
          </div>
          <div class="col-sm-6 col-xs-12">
            <%= total_sales %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if defined?(total_itens) %>
    <div class="col-sm-3 col-xs-12">
      <div class="dash">
        <div class="row">
          <div class="col-sm-6 col-xs-12">
            Itens
          </div>
          <div class="col-sm-6 col-xs-12">
            <%= total_itens %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if defined?(total_amount) %>
    <div class="col-sm-3 col-xs-12">
      <div class="dash">
        <div class="row">
          <div class="col-sm-6 col-xs-12">
            Quantidade
          </div>
          <div class="col-sm-6 col-xs-12">
            <%= total_amount %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if defined?(total_price) %>
    <div class="col-sm-3 col-xs-12">
      <div class="dash">
        <div class="row">
          <div class="col-sm-6 col-xs-12">
            Receita
          </div>
          <div class="col-sm-6 col-xs-12">
            <%= number_to_currency(
              total_price, precision: 2, unit: 'R$', separator: ','
            ) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/sales/_items.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Comprador</th>
      <th scope="col">Descrição</th>
      <th scope="col">Preço Unitário</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Endereço</th>
      <th scope="col">Fornecedor</th>
    </tr>
  </thead>
  <tbody>
    <% @sale.items.each do |item| %>
      <tr>
        <th scope="row"><%= item.buyer %></th>
        <td><%= item.description %></td>
        <td>
          <%= number_to_currency(
            item.price, precision: 2, unit: 'R$', separator: ','
          ) %>
        </td>
        <td><%= item.amount %></td>
        <td><%= item.address %></td>
        <td><%= item.vendor %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/import.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/sales">Vendas</a></li>
    <li class="breadcrumb-item active" aria-current="page">Importação</li>
  </ol>
</nav>

<h1>Dados importados</h1>

<%= notification %>

<%=
  render 'dash',
  total_itens: @sale.total_items,
  total_amount: @sale.total_amount,
  total_price: @sale.total_price
%>

<%= render 'sales/items' %>

app/views/sales/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Vendas</li>
  </ol>
</nav>

<h1>Vendas</h1>

<%=
  render 'dash',
  total_sales: Sale.total_sales,
  total_itens: SaleItem.total_items,
  total_amount: SaleItem.total_amount,
  total_price: SaleItem.total_price
%>

<p class="actions">
  <%= link_to 'Importar vendas', new_sale_path, class: "btn btn-primary"  %>
</p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Importado em</th>
      <th scope="col">Total de Itens</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Receita</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <th scope="row"><%= sale.id %></th>
        <td><%= sale.created_at.strftime("%b, %m %Y - %H:%M") %></td>
        <td><%= sale.total_items %></td>
        <td><%= sale.total_amount %></td>
        <td>
          <%= number_to_currency(
            sale.total_price, precision: 2, unit: 'R$', separator: ','
          ) %>
        </td>
        <td>
          <%= link_to "Ver itens", sale_path(sale) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/sales">Vendas</a></li>
    <li class="breadcrumb-item active" aria-current="page">Nova importação</li>
  </ol>
</nav>

<h1>Importar vendas</h1>

<%= notification %>

<%= form_tag(import_sales_path, method: "post", multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, "Arquivo (txt):") %>
    <%= file_field_tag(:file) %>
  </div>
  <button type="submit" class="btn btn-primary">Importar</button>
<% end %>

app/views/sales/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/sales">Vendas</a></li>
    <li class="breadcrumb-item active" aria-current="page">Items</li>
  </ol>
</nav>

<h1>Items</h1>

<%=
  render 'dash',
  total_itens: @sale.total_items,
  total_amount: @sale.total_amount,
  total_price: @sale.total_price
%>

<%= render 'items' %>